# frozen_string_literal: true

module Api
  # Dashboard API for the Admin Agents view: the resources connected apps
  # have reported (POST /v1/resources) and the scaffolding actions that turn
  # them into admin agents — rails_admin's model list, with "generate an
  # agent" where rails_admin has "generate screens".
  class AdminResourcesController < BaseController
    before_action :require_account!
    before_action :set_resource, only: [ :show, :generate ]

    # GET /api/admin_resources
    def index
      resources = current_account.admin_resources.includes(:agent).recent
      resources = resources.for_service(params[:service]) if params[:service].present?

      render json: {
        resources: resources.map { |resource| resource_json(resource) },
        meta: {
          total: resources.size,
          services: current_account.admin_resources.distinct.pluck(:service_name).sort
        }
      }
    end

    # GET /api/admin_resources/:id
    def show
      render json: { resource: resource_json(@resource, include_details: true) }
    end

    # POST /api/admin_resources/:id/generate
    def generate
      return render_foreign_agent_conflict if foreign_agent?(@resource)

      agent = AdminAgentScaffold.call(@resource, user: current_user)

      render json: { resource: resource_json(@resource.reload, include_details: true), agent_id: agent.id }
    end

    # POST /api/admin_resources/generate_all
    # Scaffolds admin agents for every resource of one service in a single
    # click — the "auto generate admin agents based on resources" flow. One
    # bad resource (or another member's agent) skips, never aborts the rest.
    def generate_all
      service = params.require(:service_name).to_s
      resources = current_account.admin_resources.for_service(service).recent

      generated = 0
      skipped = []
      resources.each do |resource|
        if foreign_agent?(resource)
          skipped << { name: resource.name, reason: "agent belongs to another workspace member" }
          next
        end

        AdminAgentScaffold.call(resource, user: current_user)
        generated += 1
      rescue ActiveRecord::RecordInvalid => e
        skipped << { name: resource.name, reason: e.message }
      end

      render json: {
        service_name: service,
        generated: generated,
        skipped: skipped,
        resources: resources.map { |resource| resource_json(resource.reload) }
      }
    end

    private

    def set_resource
      @resource = current_account.admin_resources.find(params[:id])
    end

    # Resources are account-scoped but agents are user-scoped everywhere in
    # the dashboard API, so regenerating a teammate's agent would silently
    # rewrite a record its owner edits and the caller can't even open.
    # Refuse instead of overwriting.
    def foreign_agent?(resource)
      resource.agent.present? && resource.agent.user_id != current_user.id
    end

    def render_foreign_agent_conflict
      render json: {
        error: "This resource's admin agent was generated by another workspace member; ask them to regenerate it."
      }, status: :conflict
    end

    def resource_json(resource, include_details: false)
      json = {
        id: resource.id,
        name: resource.name,
        service_name: resource.service_name,
        environment: resource.environment,
        table_name: resource.table_name,
        column_count: Array(resource.columns).size,
        record_count: resource.record_count,
        admin_route: resource.admin_route,
        admin_ui: resource.admin_ui?,
        schema_fingerprint: resource.schema_fingerprint,
        first_reported_at: resource.first_reported_at,
        last_reported_at: resource.last_reported_at,
        agent: resource.agent && {
          id: resource.agent.id,
          name: resource.agent.name,
          slug: resource.agent.slug,
          status: resource.agent.status,
          version_count: resource.agent.version_count,
          # Agents are user-scoped in the dashboard API; a teammate's
          # generated agent is visible here but not openable/regenerable.
          owned: resource.agent.user_id == current_user.id
        }
      }

      if include_details
        json.merge!(
          columns: resource.columns,
          associations: resource.associations,
          metadata: resource.metadata
        )
      end

      json
    end
  end
end
