version: '3.8'
services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: activeagents_development
  redis:
    ports:
      - 6379:6379
    image: redis:6