default: &default
  model: "gpt-4o"
  temperature: 0.8
  n: 1

openai: &open_ai
  <<: *default
  service: OpenAI
  project: your_project_name
  organization: your_organization
  api_key: <%= Rails.application.credentials.dig(:openai, :api_key) %>

development:
  <<: *open_ai
  model: "gpt-3.5-turbo"