require:
  - rubocop-minitest
  - rubocop-performance

AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable
  Exclude:
    - "vendor/**/*"

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

Metrics/AbcSize:
  Max: 30

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Minitest/MultipleAssertions:
  Max: 10
